import sys
import os
import django

sys.path.append(os.getcwd())
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'dosta.settings')
django.setup()

from catering.models import FixedCateringMenu, MenuItem

def force_repopulate_items():
    print("Force Repopulating Menu Items...")
    
    menus = FixedCateringMenu.objects.all()
    for menu in menus:
        print(f"Processing Menu: {menu.name}")
        
        # We want to add ALL items that match this Menu's Criterion:
        # 1. Cuisine matches
        # 2. Budget matches (via M2M on Item)
        # 3. Course matches one of the Menu's courses
        
        target_items = MenuItem.objects.filter(
            cuisine=menu.cuisine,
            budget_options=menu.budget_option, # Filter items that HAVE this budget option
            course__in=menu.courses.all()      # Filter items in one of the menu's courses
        ).distinct()
        
        count = target_items.count()
        print(f"  Found {count} eligible items in DB.")
        
        if count > 0:
            # Clear and Re-add to be safe, or just add
            # Let's just set() to be sure it exactly matches what current DB state is
            # logical for this menu definition.
            # However, set() might remove manual overrides if any?
            # Given these are Fixed Menus generated by script, it should be fine.
            # But let's just use .add() to add clean ones.
            # Actually, if we restore, old invalid IDs might be gone, but M2M table handles that.
            
            current_count = menu.items.count()
            print(f"  Current Menu Items Count: {current_count}")
            
            menu.items.set(target_items)
            print(f"  Updated Menu Items. New Count: {menu.items.count()}")
        else:
            print("  [WARNING] No items found for this menu configuration!")

    print("Force Repopulate Complete.")

if __name__ == "__main__":
    force_repopulate_items()
