# Generated by Django 5.2.7 on 2025-10-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_company_profile_email_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiration',
            field=models.CharField(help_text='MM/YYYY format', max_length=7),
        ),
    ]
