# Generated by Django 5.2.7 on 2025-10-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providertype',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
