# Generated by Django 5.2.7 on 2025-10-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0002_providertype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='image',
            field=models.FileField(upload_to='event_types/'),
        ),
        migrations.AlterField(
            model_name='providertype',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='providers/'),
        ),
    ]
