# Generated by Django 5.2.7 on 2025-10-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0003_alter_eventtype_image_alter_providertype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='image',
            field=models.FileField(upload_to='cuisines/'),
        ),
    ]
