# Generated by Django 5.2.7 on 2025-10-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0004_alter_cuisine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(upload_to='courses/'),
        ),
    ]
