# Generated by Django 5.2.7 on 2026-01-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0005_alter_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStylePrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
