# Generated by Django 5.2.7 on 2026-01-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0006_servicestyleprivate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetOptionPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('price_range', models.CharField(max_length=100)),
            ],
        ),
    ]
