# Generated by Django 5.2.7 on 2026-01-05 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0009_eventname'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cuisines',
            field=models.ManyToManyField(blank=True, related_name='courses', to='catering.cuisine'),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='menu_items/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='catering.course')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='catering.cuisine')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catering.budgetoption')),
                ('budget_option_private', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catering.budgetoptionprivate')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catering.menuitem')),
            ],
        ),
    ]
