# Generated by Django 5.2.7 on 2026-01-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0010_course_cuisines_menuitem_menuitemvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='budget_options',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='catering.budgetoption'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='budget_options_private',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='catering.budgetoptionprivate'),
        ),
        migrations.DeleteModel(
            name='MenuItemVariant',
        ),
    ]
