# Generated by Django 5.2.7 on 2026-01-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0011_menuitem_budget_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetoption',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budgetoptionprivate',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
