# Generated by Django 5.2.7 on 2026-01-06 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0012_budgetoption_max_price_budgetoptionprivate_max_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catering.menuitem')),
            ],
        ),
    ]
