# Generated by Django 5.2.7 on 2026-01-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0013_menuitemprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetoption',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='budgetoptionprivate',
            name='max_price',
        ),
    ]
