# Generated by Django 5.2.7 on 2026-01-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0015_budgetoption_max_price_budgetoptionprivate_max_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='cuisines',
            field=models.ManyToManyField(blank=True, related_name='event_types', to='catering.cuisine'),
        ),
    ]
