# Generated by Django 5.2.7 on 2026-01-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0016_eventtype_cuisines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='cuisines',
        ),
        migrations.AddField(
            model_name='servicestyle',
            name='cuisines',
            field=models.ManyToManyField(blank=True, related_name='service_styles', to='catering.cuisine'),
        ),
        migrations.AddField(
            model_name='servicestyleprivate',
            name='cuisines',
            field=models.ManyToManyField(blank=True, related_name='service_styles_private', to='catering.cuisine'),
        ),
    ]
