# Generated by Django 5.2.7 on 2026-01-07 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0017_remove_eventtype_cuisines_servicestyle_cuisines_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBreakRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeBreakItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, upload_to='coffee_break/')),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catering.coffeebreakrotation')),
            ],
        ),
    ]
