# Generated by Django 5.2.7 on 2026-01-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0018_coffeebreakrotation_coffeebreakitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestyle',
            name='budget_options',
            field=models.ManyToManyField(blank=True, related_name='service_styles', to='catering.budgetoption'),
        ),
        migrations.AddField(
            model_name='servicestyleprivate',
            name='budget_options',
            field=models.ManyToManyField(blank=True, related_name='service_styles_private', to='catering.budgetoptionprivate'),
        ),
    ]
