# Generated by Django 5.2.7 on 2026-01-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0019_servicestyle_budget_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='budget_options_private',
        ),
        migrations.AlterField(
            model_name='servicestyleprivate',
            name='budget_options',
            field=models.ManyToManyField(blank=True, related_name='service_styles_private', to='catering.budgetoption'),
        ),
        migrations.DeleteModel(
            name='BudgetOptionPrivate',
        ),
    ]
