# Generated by Django 5.2.7 on 2026-01-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0020_remove_menuitem_budget_options_private_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicestyleprivate',
            old_name='budget_options',
            new_name='budget_options_temp',
        ),
    ]
