# Generated by Django 5.2.7 on 2026-01-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0022_rename_budget_options_temp_servicestyleprivate_budget_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='platter_items/')),
            ],
        ),
    ]
