# Generated by Django 5.2.7 on 2026-01-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0023_platteritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxedMealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Salads', 'Salads'), ('Soup', 'Soup'), ('Mains', 'Mains'), ('Soft Drink', 'Soft Drink')], max_length=50)),
                ('image', models.FileField(blank=True, upload_to='boxed_meals/')),
            ],
        ),
    ]
