# Generated by Django 5.2.7 on 2026-01-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0024_boxedmealitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setup', models.TextField()),
                ('ingredients', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='live_stations/')),
            ],
        ),
    ]
