# Generated by Django 5.2.7 on 2026-01-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0025_livestationitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaxPrivate',
        ),
        migrations.AddField(
            model_name='pax',
            name='service_styles',
            field=models.ManyToManyField(blank=True, related_name='pax_options', to='catering.servicestyle'),
        ),
    ]
