# Generated by Django 5.2.7 on 2026-01-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0026_delete_paxprivate_pax_service_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='budget_options',
            field=models.ManyToManyField(blank=True, related_name='cuisines', to='catering.budgetoption'),
        ),
    ]
