# Generated by Django 5.2.7 on 2026-01-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0027_cuisine_budget_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetoption',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
