# Generated by Django 5.2.7 on 2026-01-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0028_budgetoption_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
