# Generated by Django 5.2.7 on 2026-01-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0029_cuisine_max_price_cuisine_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pax',
            name='service_styles_private',
            field=models.ManyToManyField(blank=True, related_name='pax_options', to='catering.servicestyleprivate'),
        ),
    ]
