# Generated by Django 5.2.7 on 2026-01-09 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0030_pax_service_styles_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCateringMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='fixed_menus', to='catering.course')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_menus', to='catering.cuisine')),
                ('items', models.ManyToManyField(blank=True, related_name='fixed_menus', to='catering.menuitem')),
            ],
        ),
    ]
