# Generated by Django 5.2.7 on 2026-01-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0031_fixedcateringmenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisine',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='cuisine',
            name='min_price',
        ),
        migrations.DeleteModel(
            name='FixedCateringMenu',
        ),
    ]
