# Generated by Django 5.2.7 on 2026-01-09 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0032_remove_cuisine_max_price_remove_cuisine_min_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='budget_options',
            field=models.ManyToManyField(blank=True, related_name='courses', to='catering.budgetoption'),
        ),
        migrations.CreateModel(
            name='FixedCateringMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('budget_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_menus', to='catering.budgetoption')),
                ('courses', models.ManyToManyField(blank=True, related_name='fixed_menus', to='catering.course')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_menus', to='catering.cuisine')),
                ('items', models.ManyToManyField(blank=True, related_name='fixed_menus', to='catering.menuitem')),
            ],
        ),
    ]
