# Generated by Django 5.2.7 on 2026-01-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0033_course_budget_options_fixedcateringmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestyle',
            name='min_pax',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicestyleprivate',
            name='min_pax',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
