# Generated by Django 5.2.7 on 2026-01-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0035_americanmenu_americanmenuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanapeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Cold', 'Cold Canapes'), ('Hot', 'Hot Canapes'), ('Sweet', 'Sweet Canapes')], max_length=50)),
                ('image', models.FileField(blank=True, upload_to='canapes/')),
            ],
        ),
    ]
