# Generated by Django 5.2.7 on 2026-01-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0036_canapeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canapeitem',
            name='category',
            field=models.CharField(choices=[('Cold', 'Cold Canapes'), ('Hot', 'Hot Canapes'), ('Arabic', 'Arabic Canapes'), ('Sweet', 'Sweet Canapes'), ('Vegetarian', 'Vegetarian Canapes'), ('Cold Beverages', 'Cold Beverages'), ('Hot Beverages', 'Hot Beverages')], max_length=50),
        ),
    ]
