# Generated by Django 5.2.7 on 2026-01-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0037_alter_canapeitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestyle',
            name='description',
            field=models.TextField(blank=True, default='Dummy description', null=True),
        ),
    ]
