# Generated by Django 5.2.7 on 2026-01-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0038_servicestyle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='americanmenu',
            name='description',
            field=models.TextField(blank=True, default='Dummy description', null=True),
        ),
        migrations.AddField(
            model_name='coffeebreakrotation',
            name='description',
            field=models.TextField(blank=True, default='Dummy description', null=True),
        ),
        migrations.AddField(
            model_name='fixedcateringmenu',
            name='description',
            field=models.TextField(blank=True, default='Dummy description', null=True),
        ),
    ]
