# Generated by Django 5.2.7 on 2026-01-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0039_americanmenu_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestationitem',
            name='description',
            field=models.TextField(blank=True, default='Dummy description', null=True),
        ),
    ]
