# Generated by Django 5.2.7 on 2026-01-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0041_cateringorder_cateringorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='americanmenu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fixedcateringmenu',
            name='description',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
