# Generated by Django 5.2.7 on 2026-01-30 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0042_remove_americanmenu_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringMasterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='master_catering_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='americanmenuitem',
            name='master_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='american_items', to='catering.cateringmasteritem'),
        ),
        migrations.AddField(
            model_name='boxedmealitem',
            name='master_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boxed_items', to='catering.cateringmasteritem'),
        ),
        migrations.AddField(
            model_name='canapeitem',
            name='master_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canape_items', to='catering.cateringmasteritem'),
        ),
        migrations.AddField(
            model_name='coffeebreakitem',
            name='master_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coffee_items', to='catering.cateringmasteritem'),
        ),
        migrations.AddField(
            model_name='livestationitem',
            name='master_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='live_station_items', to='catering.cateringmasteritem'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='master_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='catering.cateringmasteritem'),
        ),
        migrations.AddField(
            model_name='platteritem',
            name='master_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platter_items', to='catering.cateringmasteritem'),
        ),
    ]
