# Generated by Django 5.2.7 on 2026-02-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0043_cateringmasteritem_americanmenuitem_master_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStylePrivateChef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='Dummy description', null=True)),
                ('min_pax', models.PositiveIntegerField(default=0)),
                ('budget_options', models.ManyToManyField(blank=True, related_name='service_styles_private_chef', to='catering.budgetoption')),
                ('cuisines', models.ManyToManyField(blank=True, related_name='service_styles_private_chef', to='catering.cuisine')),
            ],
        ),
        migrations.AddField(
            model_name='pax',
            name='service_styles_private_chef',
            field=models.ManyToManyField(blank=True, related_name='pax_options', to='catering.servicestyleprivatechef'),
        ),
    ]
