# Generated by Django 5.2.7 on 2026-02-14 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0044_servicestyleprivatechef_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamadanMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ramadan_menus', to='catering.budgetoption')),
                ('service_style', models.ForeignKey(help_text='Select Iftar Menu or Sohour Menu', on_delete=django.db.models.deletion.CASCADE, related_name='ramadan_menus', to='catering.servicestyle')),
            ],
            options={
                'verbose_name': 'Ramadan Menu',
                'verbose_name_plural': 'Ramadan Menus',
                'ordering': ['service_style', 'budget_option', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RamadanMenuCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ramadan_menu_courses', to='catering.course')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_courses', to='catering.ramadanmenu')),
            ],
            options={
                'verbose_name': 'Ramadan Menu Course',
                'verbose_name_plural': 'Ramadan Menu Courses',
                'ordering': ['menu', 'display_order', 'course'],
                'unique_together': {('menu', 'course')},
            },
        ),
        migrations.CreateModel(
            name='RamadanMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='ramadan_menu_items/')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of servings or pieces')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('master_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ramadan_menu_items', to='catering.cateringmasteritem')),
                ('menu_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catering.ramadanmenucourse')),
            ],
            options={
                'verbose_name': 'Ramadan Menu Item',
                'verbose_name_plural': 'Ramadan Menu Items',
                'ordering': ['menu_course', 'display_order', 'name'],
            },
        ),
    ]
