# Generated by Django 5.2.7 on 2026-02-25 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0045_ramadanmenu_ramadanmenucourse_ramadanmenuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='IftarBoxMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional name for this Iftar Box Menu', max_length=200, null=True)),
                ('image', models.FileField(help_text='Upload the image containing the Iftar Box Menu', upload_to='iftar_box_menus/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iftar_box_menus', to='catering.budgetoption')),
            ],
            options={
                'verbose_name': 'Iftar Box Menu',
                'verbose_name_plural': 'Iftar Box Menus',
                'ordering': ['budget_option', 'name'],
            },
        ),
    ]
