# Generated by Django 5.2.7 on 2026-03-15 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0046_iftarboxmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='SweetsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='Dummy description', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.FileField(blank=True, upload_to='sweets_items/')),
                ('master_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sweets_items', to='catering.cateringmasteritem')),
            ],
        ),
        migrations.CreateModel(
            name='SweetsItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='sweets_items/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('sweets_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catering.sweetsitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SweetsItemVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(help_text='e.g., 1kg, 0.5kg, 250g', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sweets_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='catering.sweetsitem')),
            ],
        ),
    ]
