# Generated by Django 5.2.8 on 2025-12-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='week_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='Week number (1-4) for monthly rotation'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.PositiveIntegerField(default=0, help_text='kcal'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='carbs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='grams', max_digits=6),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='fats',
            field=models.DecimalField(decimal_places=2, default=0, help_text='grams', max_digits=6),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, help_text='grams', max_digits=6),
        ),
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
