# Generated by Django 5.2.8 on 2025-12-26 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0004_menu_week_number_menuitem_calories_menuitem_carbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='pickup_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='vending.pickuptimeslot'),
        ),
        migrations.AddField(
            model_name='cart',
            name='pickup_type',
            field=models.CharField(blank=True, choices=[('TODAY', 'Pickup today'), ('IN_24_HOURS', 'Pickup in 24 hours')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='plan_subtype',
            field=models.CharField(choices=[('NONE', 'None'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='cart',
            name='plan_type',
            field=models.CharField(choices=[('ORDER_NOW', 'Order now'), ('START_PLAN', 'Start a plan'), ('SMART_GRAB', 'Smart grab')], default='ORDER_NOW', max_length=20),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='week_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
