# Generated by Django 5.2.8 on 2025-12-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0005_cart_pickup_date_cart_pickup_slot_cart_pickup_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='current_step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
