# Generated by Django 5.2.7 on 2026-01-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0006_cart_current_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendinglocation',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
