# Generated by Django 5.2.7 on 2026-01-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0007_vendinglocation_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='vending_good_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vending_good_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
