# Generated by Django 5.2.7 on 2026-01-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0008_cartitem_vending_good_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='qr_code_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
