# Generated by Django 5.2.7 on 2026-01-10 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0009_order_pickup_code_order_qr_code_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pickup_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items_context', to='vending.pickuptimeslot'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pickup_type',
            field=models.CharField(blank=True, choices=[('TODAY', 'Pickup today'), ('IN_24_HOURS', 'Pickup in 24 hours')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='plan_subtype',
            field=models.CharField(choices=[('NONE', 'None'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='plan_type',
            field=models.CharField(choices=[('ORDER_NOW', 'Order now'), ('START_PLAN', 'Start a plan'), ('SMART_GRAB', 'Smart grab')], default='ORDER_NOW', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pickup_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='vending.pickuptimeslot'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pickup_type',
            field=models.CharField(blank=True, choices=[('TODAY', 'Pickup today'), ('IN_24_HOURS', 'Pickup in 24 hours')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='plan_subtype',
            field=models.CharField(choices=[('NONE', 'None'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='plan_type',
            field=models.CharField(choices=[('ORDER_NOW', 'Order now'), ('START_PLAN', 'Start a plan'), ('SMART_GRAB', 'Smart grab')], default='ORDER_NOW', max_length=20),
        ),
    ]
