# Generated by Django 5.2.7 on 2026-01-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0010_cartitem_pickup_date_cartitem_pickup_slot_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'menu_item', 'plan_type', 'plan_subtype', 'day_of_week', 'week_number')},
        ),
    ]
