# Generated by Django 5.2.7 on 2026-01-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0011_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendingMachineStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vending_good_uuid', models.CharField(max_length=255, unique=True)),
                ('goods_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
