# Generated by Django 5.2.7 on 2026-01-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0012_vendingmachinestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='heating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
