# Generated by Django 5.2.7 on 2026-01-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0013_menuitem_heating_menuitem_image_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='heating_requested',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='heating_requested',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, null=True),
        ),
    ]
