# Generated by Django 5.2.7 on 2026-01-30 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending', '0014_cartitem_heating_requested_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('calories', models.PositiveIntegerField(default=0, help_text='kcal')),
                ('protein', models.DecimalField(decimal_places=2, default=0, help_text='grams', max_digits=6)),
                ('carbs', models.DecimalField(decimal_places=2, default=0, help_text='grams', max_digits=6)),
                ('fats', models.DecimalField(decimal_places=2, default=0, help_text='grams', max_digits=6)),
                ('heating', models.BooleanField(default=False)),
                ('image_source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='master_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='vending.masteritem'),
        ),
    ]
