# Generated by Django 5.2.7 on 2026-03-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0047_sweetsitem_sweetsitemimage_sweetsitemvariation'),
        ('vending', '0015_masteritem_menuitem_master_item'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sweets_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='catering.sweetsitem'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sweets_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='catering.sweetsitemvariation'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sweets_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catering.sweetsitem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sweets_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catering.sweetsitemvariation'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='vending.menuitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='vending.menuitem'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'menu_item', 'sweets_item', 'sweets_variation', 'plan_type', 'plan_subtype', 'day_of_week', 'week_number')},
        ),
    ]
