# Generated by Django 5.2.7 on 2026-03-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(default='marketing', max_length=50)),
                ('platform', models.CharField(choices=[('Meta', 'Meta (Facebook/Instagram)'), ('Google', 'Google Ads')], max_length=20)),
                ('headline', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('targeting_summary', models.TextField(help_text='Human-readable targeting description')),
                ('targeting_data', models.JSONField(blank=True, default=dict, help_text='Raw API targeting parameters')),
                ('budget', models.DecimalField(decimal_places=2, help_text='Daily budget in AED', max_digits=10)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Live', 'Live'), ('Failed', 'Failed')], default='Pending Approval', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('platform_ad_id', models.CharField(blank=True, help_text='ID returned by Meta/Google after going live', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(help_text='e.g., sales, customer_service', max_length=50, unique=True)),
                ('name', models.CharField(help_text='The display name of the agent', max_length=255)),
                ('role', models.TextField(help_text='The primary system persona/role definition')),
                ('knowledge', models.TextField(blank=True, help_text='Specific background knowledge, current deals, menu changes, etc.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AIGlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('state', models.CharField(default='START', max_length=100)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('agent_type', models.CharField(blank=True, max_length=50, null=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('loop_counter', models.IntegerField(default=0)),
                ('is_bot', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('preference', models.CharField(help_text='Event Type or Menu selection', max_length=255)),
                ('event_date', models.CharField(blank=True, max_length=100, null=True)),
                ('event_time', models.CharField(blank=True, max_length=100, null=True)),
                ('people_count', models.CharField(blank=True, max_length=100, null=True)),
                ('venue', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Customer Inquiries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CustomerServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('subject', models.CharField(default='Complaint/Suggestion', max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('meta_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('google_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ai_analysis_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Failed', 'Failed')], default='New', max_length=20)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('date_scraped', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScraperSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.TimeField(default='09:00:00')),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_automated_run', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScraperStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('current_source', models.CharField(blank=True, max_length=255, null=True)),
                ('leads_found', models.IntegerField(default=0)),
                ('last_run_time', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='DISCONNECTED', max_length=50)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='agentactivity',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
